# Generated by Django 4.1.3 on 2022-12-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admreg_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admname', models.CharField(max_length=255)),
                ('admemail', models.CharField(max_length=255)),
                ('admpassword', models.CharField(max_length=255)),
            ],
        ),
    ]
