# Generated by Django 4.1.3 on 2022-12-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=255)),
                ('fdescription', models.CharField(max_length=255)),
                ('fimg', models.ImageField(upload_to='product/')),
            ],
        ),
    ]
