# Generated by Django 4.1.3 on 2022-12-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_menu_tb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_tb',
            name='fdescription',
            field=models.TextField(),
        ),
    ]
