# Generated by Django 4.1.3 on 2022-12-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_alter_menu_tb_fdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='cont_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=255)),
                ('cemail', models.CharField(max_length=255)),
                ('cpnumber', models.CharField(max_length=255)),
                ('cmsg', models.TextField()),
            ],
        ),
    ]
