# Generated by Django 4.1.3 on 2022-12-12 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0004_cont_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservation_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=255)),
                ('remail', models.CharField(max_length=255)),
                ('rphone', models.CharField(max_length=255)),
                ('raddress', models.CharField(max_length=255)),
                ('rcity', models.CharField(max_length=255)),
                ('rstate', models.CharField(max_length=255)),
                ('rzipcode', models.CharField(max_length=255)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodapp.menu_tb')),
            ],
        ),
    ]
