# Generated by Django 4.1.3 on 2022-12-14 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0006_galleryup_tb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cont_tb',
        ),
    ]
